### ISSUE TITLE
qres30m mean and std computed on imagenet

### ISSUE THREAD

**Issue by jjeremy40** [duanzhiihao/qres-vae#4]
Hi,

I'm currently doing a PhD at Université Paris 13 in Paris and I'm looking for Image Compression deep learning algorithms.

Yours is particularly interesting and I'm trying to train it on my own dataset (Waymo), but I'm running into some trouble...

I figured that my pb comes from qres30m in the library.py file : 
![image](https://user-images.githubusercontent.com/44731689/212289398-1f55de4a-6ccc-48eb-8289-cfa537d1ad9c.png)

Could you explain to me how did you get those shift and scale values pls ?

Help will be very much appreciated.

Thank you in advance.

**Comment by duanzhiihao** [comment]
Hi,
Thank you for your interest. 

Regarding `cfg.im_shift` and `cfg.im_scale`, they are the mean and standard deviation, respectively, computed on the imagenet 64x64 dataset.

I use these values simply because I developed my code starting from https://github.com/openai/vdvae, which uses these specific `shift` and `scale` for its imagenet model (see here https://github.com/openai/vdvae/blob/ea35b490313bc33e7f8ac63dd8132f3cc1a729b4/data.py#L24).
Note that the `shift` and scale` in VDVAE are for 0-255 pixel values, while I convert them to  0-1 pixel value range.

Could you elaborate on why `cfg.im_shift` and `cfg.im_scale` cause problems?
In fact, there is nothing special with these numbers. If you are training new models, you can simply set them to be for example 
```
cfg.im_shift = 0
cfg.im_scale = 1
```
and the model performance won't noticeably change.

**Comment by jjeremy40** [comment]
My bad, the pb was caused by a misprint : 
im_shift = [0.3272 ,0.3594, 3899] instead of [0.3272 ,0.3594, 0.3899] which caused the gradient to explode ...
Thanks for your explanation !
